/** Supported South African languages for audio */
export type AudioLanguage = 'en-ZA' | 'af-ZA' | 'zu-ZA';

/** A single audio file entry in the audio map */
export interface AudioFileEntry {
  /** Path relative to /audio/ (e.g. "edge-tts/encouragement/enc_great_en-ZA.mp3") */
  path: string;
  /** File size in KB */
  size_kb: number;
}

/**
 * Audio map entry: keyed by language code or "all" for language-independent sounds.
 * Language-specific entries use "en-ZA", "af-ZA", "zu-ZA".
 * Language-independent entries (UI sounds) use "all".
 */
export type AudioMapEntry = {
  [key in AudioLanguage | 'all']?: AudioFileEntry;
};

/**
 * Complete audio map: maps audio IDs to their language variants.
 * Generated by scripts/audio/run_pipeline.py --map
 * Served from public/audio/audio_map.json
 */
export type AudioMap = Record<string, AudioMapEntry>;

/** Audio categories from the pipeline manifest */
export type AudioPipelineCategory =
  | 'phonics'
  | 'narration'
  | 'encouragement'
  | 'instructions'
  | 'ui_sounds';

/** Encouragement clip IDs */
export type EncouragementId =
  | 'enc_great'
  | 'enc_amazing'
  | 'enc_tryagain'
  | 'enc_keepgoing'
  | 'enc_star'
  | 'enc_proud'
  | 'enc_rainbow'
  | 'enc_ubuntu'
  | 'enc_together'
  | 'enc_gentle_redirect';

/** Instruction clip IDs */
export type InstructionId =
  | 'inst_drag'
  | 'inst_tap'
  | 'inst_listen'
  | 'inst_count'
  | 'inst_trace'
  | 'inst_coin_match'
  | 'inst_color_pick';

/** Phonics clip IDs */
export type PhonicsId =
  | 'phon_a'
  | 'phon_b'
  | 'phon_c'
  | 'phon_d'
  | 'phon_e'
  | 'phon_m'
  | 'phon_s'
  | 'phon_t';

/** UI sound IDs */
export type UiSoundId =
  | 'ui_tap'
  | 'ui_success'
  | 'ui_gentle_error'
  | 'ui_star_collect'
  | 'ui_level_up'
  | 'ui_coin_drop'
  | 'ui_whoosh'
  | 'ui_pop';

/** All pipeline audio IDs */
export type PipelineAudioId =
  | EncouragementId
  | InstructionId
  | PhonicsId
  | UiSoundId;
