import type { Character, Companion, CoreCharacterId, CompanionId } from './game';

export const CHARACTERS: Record<CoreCharacterId, Character> = {
  gogo_thandi: {
    id: 'gogo_thandi',
    fullName: 'Gogo Thandi',
    role: 'wisdom_keeper',
    ethnicity: 'Xhosa elder',
    companion: 'elephant_calf',
    skinTone: '#6D4C41',
    languages: ['EN', 'XH', 'AF'],
    catchphrase: { en: 'Wisdom grows when we share it.' },
    vertices: 650,
  },
  sipho: {
    id: 'sipho',
    fullName: 'Sipho Dlamini',
    role: 'curious_explorer',
    ethnicity: 'Zulu',
    companion: 'springbok',
    skinTone: '#8D6E63',
    languages: ['EN', 'ZU'],
    catchphrase: { en: "Let's discover together!" },
    vertices: 500,
  },
  amahle: {
    id: 'amahle',
    fullName: 'Amahle Ndlovu',
    role: 'caring_helper',
    ethnicity: 'Zulu/Xhosa',
    companion: 'meerkat',
    skinTone: '#795548',
    languages: ['EN', 'ZU', 'AF'],
    catchphrase: { en: 'I am here to help!' },
    vertices: 500,
  },
  jabu: {
    id: 'jabu',
    fullName: 'Jabu Mokoena',
    role: 'creative_builder',
    ethnicity: 'Sotho',
    companion: 'weaver_bird',
    skinTone: '#5D4037',
    languages: ['EN', 'ST'],
    catchphrase: { en: "Let's build something amazing!" },
    vertices: 550,
  },
  liya: {
    id: 'liya',
    fullName: 'Liya Abrahams',
    role: 'joyful_storyteller',
    ethnicity: 'Cape Malay',
    companion: 'cape_penguin',
    skinTone: '#A1887F',
    languages: ['EN', 'AF'],
    catchphrase: { en: 'Every story matters!' },
    vertices: 520,
  },
  themba: {
    id: 'themba',
    fullName: 'Themba van der Merwe',
    role: 'gentle_protector',
    ethnicity: 'Afrikaans/mixed',
    companion: 'tortoise',
    skinTone: '#BCAAA4',
    languages: ['EN', 'AF'],
    catchphrase: { en: 'I will keep you safe.' },
    vertices: 530,
  },
};

export const COMPANIONS: Record<CompanionId, Companion> = {
  elephant_calf: {
    id: 'elephant_calf',
    animal: 'Elephant Calf',
    belongsTo: 'gogo_thandi',
    vertices: 450,
    sounds: ['trumpet', 'rumble'],
  },
  springbok: {
    id: 'springbok',
    animal: 'Springbok',
    belongsTo: 'sipho',
    vertices: 300,
    sounds: ['bleat', 'hop'],
  },
  meerkat: {
    id: 'meerkat',
    animal: 'Meerkat',
    belongsTo: 'amahle',
    vertices: 250,
    sounds: ['chirp', 'squeak'],
  },
  weaver_bird: {
    id: 'weaver_bird',
    animal: 'Weaver Bird',
    belongsTo: 'jabu',
    vertices: 200,
    sounds: ['chirp', 'tweet'],
  },
  cape_penguin: {
    id: 'cape_penguin',
    animal: 'Cape Penguin',
    belongsTo: 'liya',
    vertices: 280,
    sounds: ['honk', 'waddle'],
  },
  tortoise: {
    id: 'tortoise',
    animal: 'Tortoise',
    belongsTo: 'themba',
    vertices: 220,
    sounds: ['shuffle', 'munch'],
  },
};

/** Performance budget constants */
export const BUDGETS = {
  MAX_BUNDLE_KB: 500,
  MAX_ASSET_KB: 50,
  MAX_TEXTURE_SIZE: 512,
  MAX_TRIANGLES: 5000,
  TARGET_FPS: 30,
  MIN_FPS: 24,
  TARGET_LOAD_S: 3,
  MAX_LOAD_S: 5,
  MAX_MEMORY_MB: 200,
} as const;
